# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml



# Swagger API
springdoc:
  # openAPI ?? ??. default ?? /v3/api-docs ??.
  api-docs:
    path: /api-docs

  swagger-ui:
    # swagger-ui ?? ??. default ?? /swagger-ui.html??.
    path: /swagger-ui-custom.html

    # ? API? ?? ?? ??
    # path, query, body, response ??? ??
    groups-order: DESC

    # ?? ?? ??.
    # alpha: ??? ? ??
    # method: OpenAPI specification file? ??? ?? ?? ?? ?? ??
    tags-sorter: alpha

    # ???? ?? ??.
    # method? delete - get - patch - post - put ??? ????.
    # alpha? ??? ??? ??? ??? ? ??.
    operations-sorter: method

    # swagger-ui default url? petstore html? ???? ??
    disable-swagger-default-url: true

    # swagger-ui?? try ?? ? request duration? ???? ??
    display-request-duration: true

    mybatis:
      configuration:
        map-underscore-to-camel-case=true:

# OAuth2

  spring:
    security:
      oauth2:
        client:
          clientId: #인증번호
          clientSecret:  #인증번호
